# Generated by Django 4.2.3 on 2023-07-14 15:00

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nb_niveau', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Valeur non valide !', regex='^(\\d){1,3}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.FileField(blank=True, upload_to='')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(blank=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cycle')),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricule', models.CharField(max_length=200, unique=True, unique_for_year=True)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('acte_naissance', models.FileField(upload_to='students_files/<django.db.models.fields.CharField>_<django.db.models.fields.CharField>/', verbose_name='Votre acte de  naissance')),
                ('attestation_bac', models.FileField(upload_to='students_files/')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cycle')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filiere')),
                ('frais', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.frais')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.niveau')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
            bases=('accounts.users',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
